### ISSUE TITLE
Rake Aborted ActiveRecord::RecordInvalid: Validation failed: Repository url is not valid or accessible

### ISSUE THREAD

**Issue by cdbessig** [zendesk/samson#420]
I am getting the following when trying to run the script/bootstrap to do the initial setup.

rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Repository url is not valid or accessible
/usr/local/rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/validations.rb:79:in `raise_record_invalid'

I am trying to do just a simple install and this is my first time attempting to install samson.  Not sure where to look, background is not in Ruby.  Thanks!

**Comment by sandlerr** [comment]
Could you show the entire output of `script/bootstrap` please?

**Comment by steved** [comment]
This is most likely caused by an invalid github+ssh setup for the user you are running `script/bootstrap` from. We create a [test project](https://github.com/zendesk/samson/blob/master/db/seeds.rb#L15) and if it's inaccessible that error will be raised. Make sure you can `git clone git@github.com:samson-test-org/example-project.git`.

**Comment by gabetax** [comment]
@cdbessig I believe this should have been fixed by #447, and would be caused if your environment doesn't have an ssh key assigned to a github user. If not, follow up and we'll have a look.

**Comment by ui-deploybs** [comment]
still getting 
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Repository url is not valid or accessible
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/validations.rb:43:in `save!'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/transactions.rb:291:in `block in save!'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/transactions.rb:291:in `save!'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/persistence.rb:51:in `create!'
/home/deploy/samson/db/seeds.rb:13:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:547:in `load_seed'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/home/deploy/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)

keys for current user is even associated with github account

**Comment by steved** [comment]
Any more info you can provide? Can you run that git clone manually? Can you check the log files? The actual git output should be logged there.

**Comment by ycfreeman** [comment]
i got this same error, and end up fixed it by updating git to the required version.
git from centos 6 is 1.7.1 from default repo,
while the requirement of samson is 1.7.2.
here's a link on how to enable RPMForge and update git: http://itekblog.com/update-git-centos/

**Comment by jgoerz** [comment]
fyi, I got this same error while trying to seed the database with projects that referred to private repositories.  

Setup:
* stock Samson Dockerfile (current repo tag as of this writing is: v1992)
* Using custom seed functionality #2440 
* Only projects were affected, if you don't need to load projects, all this is overkill.  Users, Commands, etc. worked just fine.
* Mysql database on the host
* This was for a local dev setup, so I'm focusing on it working rather than best security ever, but it'd be great if folks still comment to educate me about that.

Bind mounting the SSH_AUTH_SOCK was not enough, it kept asking me for my password.  There were 4 things that were important:

* I had to create a user whose uid/gid matched what was on my local setup.  I can't see how you would get around this in production either; yet.
*  I needed to get git to load my ssh config
*  I needed to disable StrictHostKeyChecking.  I got lucky on this one... glad it was sitting in my .ssh/config commented out.
* You need to bind mount all the above plus your SSH keys... and don't think you'll get away with using nice dynamic things like $HOME, $USER, and symlinks.  I'm not completely sure about this one, except for $HOME, you can't use that inside the container.  Just be explicit.  You'll be happier :-)

Sample Dockerfile that worked for me (the horizontal scrolling is not my fault; does anyone really have 80 character wide terminals any more?):
```
# Run this command to test seeding and problems:
#
# docker run --rm -it --tty --publish 9080:9080 --net=host --dns=10.X.X.X -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent -v $HOME/tmp/phony-home:/home/appuser:ro -u 1000:1000 samson:ps-1.0.0 
#
# What args mean:
# --detach: daemonize
# --publish: map host port 9080 to container port 9080
# --net: use the hosts network interface
# --dns: This is only necessary if you're not in the office and on the VPN.  Value retrieved via nslookup.
# -v $SSH_AUTH_SOCK...  Bind mount so your ssh-agent works with git-ssh. https://gist.github.com/d11wtq/8699521
# -v $HOME/tmp/phony-home... Bind mount for your ssh keys and config.  Contains .ssh folder with
# 0700 perms.  config file (see below) and your ssh keys.  Make sure your keys are named id_rsa and
# id_rsa.pub.  No symlinks, it doesn't work.  Contents of config file:
# ----------8<-------------
# StrictHostKeyChecking no  # <--- This was necessary for me, might be an issue with my setup
# ForwardAgent yes
# 
# Host git.plansource.com
#   User git
#   HostName git.plansource.com
#   IdentityFile /home/appuser/.ssh/id_rsa  # <-- must use absolute path, this is key (haha)
#   ForwardAgent yes
# ----------8<-------------

FROM ruby:2.4.1-slim

RUN apt-get update && apt-get install -y build-essential libmysqlclient-dev libpq-dev libsqlite3-dev wget apt-transport-https git curl \
  && rm -rf /var/lib/apt/lists/*
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install nodejs

WORKDIR /app

# Mostly static
COPY config.ru /app/
COPY Rakefile /app/
COPY bin /app/bin
COPY public /app/public
COPY db /app/db
COPY .ruby-version /app/.ruby-version

# NPM
COPY package.json /app/package.json
RUN npm install

# Gems
COPY Gemfile /app/
COPY Gemfile.lock /app/
COPY vendor/cache /app/vendor/cache
COPY plugins /app/plugins

# RUN bundle install --quiet --local --jobs 4 || bundle check
RUN bundle install --with mysql2 --local --jobs 4 || bundle check

# Code
COPY config /app/config
COPY app /app/app
COPY lib /app/lib

# Assets
COPY vendor/assets /app/vendor/assets
RUN echo "takes 5 minute" && RAILS_ENV=production PRECOMPILE=1 bundle exec rake assets:precompile

# app, mysql, ldap, ldap, ssh
EXPOSE 9080 3306 389 3268 22

# Use custom seed functionality. https://github.com/zendesk/samson/pull/2440
COPY custom /app/custom/
COPY custom/start.sh /app/entry-point.sh

# Note: appuser in the container will have access to anything the user with uid:gid (1000:1000 in
# this case ) has on the host.
RUN groupadd -g 1000 appuser && useradd -r -u 1000 -g 1000 appuser \
  && mkdir -p /home/appuser && chmod 0700 /home/appuser \
  && chown -R appuser:appuser /app

ENV RAILS_ENV development

# Disable environment check is needed if RAILS_ENV is set to production
# Warning: This destroys all your data if this is set and RAILS_ENV is set production. This probably
#          only makes sense the first time, or in severe disaster recovery where you need to get
#          back up quickly... or development environments where we chose the red pill.
# ENV DISABLE_DATABASE_ENVIRONMENT_CHECK 1

# DATABASE_USER is only needed if the user is not part of the the DATABASE_URL
# ENV DATABASE_USER root

ENV DATABASE_PASSWORD password

# TODO set with production IP/hostname
# ENV DATABASE_URL mysql://root@127.0.0.1:3306

# You can't use this method for CMD, bin/setup will exit.. so we need an entrypoint script that
# allows us to do both.
# CMD ["bin/setup", "||", "bundle", "exec", "puma", "-C", "./config/puma.rb"]
CMD ["./entry-point.sh"]`

# Contents of entry-point.sh
# ----------8<-------------
# #!/usr/bin/env bash
# bin/setup
# bundle exec puma -C ./config/puma.rb
# ----------8<-------------

```

**Comment by cdbessig** [comment]
Hello,

Thank you for your email. Please note, during the holidays I am traveling and have an extended OOO schedule.

Please see the below schedule:

12/21 - OOO
12/22 - OOO
12/26 - OOO
12/27 - WORKING - book a time here: https://securedatatransit.youcanbook.me/  
12/28 - OOO
12/29 - OOO

If you wish to book a call with me on 12/27, you can use the following link to schedule a time: https://securedatatransit.youcanbook.me/  If you are a sales rep hoping to do business with us, please do not book a time, please follow up with me upon my return.

During my days out of the office, I will have limited or ZERO access to email and phone.  If you require an immediate response, please reach out to the general support email.  Otherwise, I will answer your request as soon as possible.

General Support / Technical Issues
support@creatingdigital.com
Phone 201-475-1288

Thank you for your understanding.

**Comment by grosser** [comment]
thx for the detailed writeup!
